[video]
frame_rate = 155.0                       # Hz 
# had set ROI but now using mask instead
#roi = {x_offset = 125, y_offset = 30, width = 490, height = 420} # Region of interest, pixels

[mask]
mask = "./open_field_mask1.png"

[hsv_green]
erode = 1                               # Pixels                        
dilate = 7                              # Pixels
tune = false                             # Provide sliders for tuning hsv thresholds
h_thresholds = {min = 030, max = 080}   # Hue pass band
s_thresholds = {min = 140, max = 250}   # Saturation pass band 
v_thresholds = {min = 000, max = 070}   # Value pass band

[hsv_blue]
erode = 1                               # Pixels                        
dilate = 8                              # Pixels
tune = false                             # Provide sliders for tuning hsv thresholds
h_thresholds = {min = 060, max = 130}   # Hue pass band
s_thresholds = {min = 111, max = 256}   # Saturation pass band 
v_thresholds = {min = 087, max = 256}   # Value pass band

[kalman]
dt = 0.03333333                         # Real-world sample period, seconds 
                                        # In this case, this is from frame rate of VT1 video
										# which is 30 FPS 
not_found_timeout = 10.0                # Seconds 
sigma_accel = 1000.0                    # Pixels/sec^2 
sigma_noise = 7.0                    	# Noise measurement (pixels)    
tune = true                             # Use the GUI to tweak parameters
